// docs/docs/views/00_微前端/00_micro-frontend/24.项目实战5：使用通信让独立的应用协作/supply-chain/packages/ui-vue/src/components/Input.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'

import { cn } from '../lib/utils'

withDefaults(
  defineProps<{
    modelValue?: string
    type?: string
    placeholder?: string
    autocomplete?: string
    disabled?: boolean
    class?: HTMLAttributes['class']
  }>(),
  {
    modelValue: '',
    type: 'text',
    placeholder: '',
    autocomplete: 'off',
    disabled: false,
    class: '',
  },
)

const emit = defineEmits<{ 'update:modelValue': [value: string] }>()
</script>

<template>
  <input
    :value="modelValue"
    :type="type"
    :placeholder="placeholder"
    :autocomplete="autocomplete"
    :disabled="disabled"
    :class="
      cn(
        'flex h-10 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-blue-500/20 disabled:opacity-50',
        $props.class,
      )
    "
    @input="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
  />
</template>

// docs/docs/views/00_微前端/00_micro-frontend/21.项目实战2：应用与业务说明/supply-chain/packages/ui-react/src/components/input.tsx
import type { InputHTMLAttributes } from 'react'

import { cn } from '../lib/utils'

export function Input({
  className,
  type = 'text',
  ...props
}: InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      type={type}
      className={cn(
        'flex h-10 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:ring-2 focus:ring-blue-500/20 disabled:opacity-50',
        className,
      )}
      {...props}
    />
  )
}
