// docs/docs/views/00_微前端/00_micro-frontend/23.项目实战4：自定义封装micro-router路由适配/supply-chain/apps/fulfillment-app/src/views/NotFoundView.vue
<template>
  <main class="grid min-h-screen place-items-center p-6 text-center">
    <div>
      <p class="text-7xl font-bold text-primary">404</p>
      <h1 class="mt-4 text-2xl font-semibold">页面不存在</h1>
      <p class="mt-2 text-sm text-muted-foreground">当前地址没有对应的履约业务页面。</p>
      <RouterLink
        to="/"
        class="mt-6 inline-block rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground"
        >返回履约概览</RouterLink
      >
    </div>
  </main>
</template>

// docs/docs/views/00_微前端/00_micro-frontend/21.项目实战2：应用与业务说明/supply-chain/apps/settlement-app/src/views/NotFoundView.tsx
import { Link } from 'react-router-dom'

export function Component() {
  return (
    <main className="grid min-h-screen place-items-center p-6 text-center">
      <div>
        <p className="text-7xl font-bold text-primary">404</p>
        <h1 className="mt-4 text-2xl font-semibold">页面不存在</h1>
        <p className="mt-2 text-sm text-muted-foreground">当前地址没有对应的结算业务页面。</p>
        <Link
          to="/"
          className="mt-6 inline-block rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground"
        >
          返回结算概览
        </Link>
      </div>
    </main>
  )
}
