// docs/docs/views/00_微前端/micro-frontend/04-10.micro-app框架的使用/代码/micro-lesson/sub/vue2-demo/src/views/About.vue
<template>
  <div>
    <h2>About页面</h2>
    <button @click="sendData">子应用反馈的数据</button>
  </div>
</template>

<script>
export default {
  data() {
    return {};
  },
  methods: {
    sendData() { 
      console.log(window);
      window.microApp.dispatch({
        type: "子应用发送的数据",
        path: "/app-react-demo/about"
      })
    }
  }
};
</script>

<style scoped></style>

// docs/docs/views/00_微前端/micro-frontend/18.手写micro-app-数据通信/代码/micro-lesson/sub/react-demo/src/views/About.js
import React from 'react'

export default function About() {
  return (
    <div>
      <h2>About</h2>
      <button onClick={() => { 
        window.globalStr = 'hello react 子应用';
        console.log(window.globalStr);
        console.log(window);
      }}>点击改变globalStr</button>
    </div>
  )
}
