// docs/docs/views/00_微前端/00_micro-frontend/23.项目实战4：自定义封装micro-router路由适配/supply-chain/apps/fulfillment-app/src/views/PageHeader.vue
<script setup lang="ts">
import { Button } from '@supply-chain/ui-vue'
import { RefreshCw } from 'lucide-vue-next'

defineProps<{ title: string; description: string; loading?: boolean }>()
defineEmits<{ refresh: [] }>()
</script>

<template>
  <header class="mb-6 flex flex-wrap items-start justify-between gap-4">
    <div>
      <h1 class="text-2xl font-bold tracking-tight">{{ title }}</h1>
      <p class="mt-1 text-sm text-muted-foreground">{{ description }}</p>
    </div>
    <Button variant="outline" :disabled="loading" @click="$emit('refresh')">
      <RefreshCw class="mr-2" :size="16" />刷新数据
    </Button>
  </header>
</template>

// docs/docs/views/00_微前端/00_micro-frontend/22.项目实战3：qiankun接入、登录与企业级认证架构/supply-chain/apps/settlement-app/src/views/PageHeader.tsx
import { Button } from '@supply-chain/ui-react'
import { RefreshCw } from 'lucide-react'

export default function PageHeader({
  title,
  description,
  loading,
  onRefresh,
}: {
  title: string
  description: string
  loading?: boolean
  onRefresh: () => void
}) {
  return (
    <header className="mb-6 flex flex-wrap items-start justify-between gap-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">{title}</h1>
        <p className="mt-1 text-sm text-muted-foreground">{description}</p>
      </div>
      <Button variant="outline" disabled={loading} onClick={onRefresh}>
        <RefreshCw className="mr-2" size={16} />
        刷新数据
      </Button>
    </header>
  )
}
