// apps/elpis-demo/demo/练习/react/react-helloworld/src/components/条件渲染/index.jsx
import React from 'react';

export default class 条件渲染 extends React.Component {

    state = {
        visible: true,
    };

    toggle() {
        this.setState({
            visible: !this.state.visible,
        });
    }

    createHelloWorld() {
        if (this.state.visible) {
            return <div>hello world</div>;
        }
        return null;
    }

    render() {
        return (
            <div>
                { this.createHelloWorld() }
                {/* { this.state.visible ? <div>hello world</div> : null } */}
                {/* { this.state.visible && <div>hello world</div> } */}
                <button onClick={ this.toggle.bind(this) }>
                    { this.state.visible ? '隐藏' : '显示' }
                </button>
            </div>
        );
    }

}

// apps/elpis-demo/demo/练习/vue2-test/src/components/条件渲染.vue
<template>
  <div>
    <span v-if="visible">hello world!</span>
    <button @click="hide">
      {{ visible ? '隐藏' : '显示' }}
    </button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      visible: true,
    }
  },
  methods: {
    hide() {
      this.visible = !this.visible
    },
  },
}
</script>
