// docs/docs/views/00_微前端/00_micro-frontend/24.项目实战5：使用通信让独立的应用协作/supply-chain/packages/ui-react/src/components/theme-toggle.tsx
import {
  getResolvedTheme,
  initializeTheme,
  THEME_CHANGE_EVENT,
  toggleTheme,
  type ResolvedTheme,
} from '@supply-chain/design-tokens/theme'
import { Moon, Sun } from 'lucide-react'
import { useEffect, useState } from 'react'

import { Button } from './button'

export function ThemeToggle() {
  const [theme, setTheme] = useState<ResolvedTheme>(() => getResolvedTheme())

  useEffect(() => {
    setTheme(initializeTheme())
    const syncTheme = () => setTheme(getResolvedTheme())
    window.addEventListener(THEME_CHANGE_EVENT, syncTheme)
    return () => window.removeEventListener(THEME_CHANGE_EVENT, syncTheme)
  }, [])

  const label = theme === 'dark' ? '切换为浅色主题' : '切换为深色主题'

  return (
    <Button
      variant="outline"
      size="sm"
      className="size-9 px-0"
      aria-label={label}
      onClick={() => setTheme(toggleTheme())}
    >
      {theme === 'dark' ? <Sun size={16} /> : <Moon size={16} />}
    </Button>
  )
}

// docs/docs/views/00_微前端/00_micro-frontend/21.项目实战2：应用与业务说明/supply-chain/packages/ui-vue/src/components/ThemeToggle.vue
<script setup lang="ts">
import {
  getResolvedTheme,
  initializeTheme,
  THEME_CHANGE_EVENT,
  toggleTheme,
  type ResolvedTheme,
} from '@supply-chain/design-tokens/theme'
import { Moon, Sun } from 'lucide-vue-next'
import { onBeforeUnmount, onMounted, ref } from 'vue'

import Button from './Button.vue'

const currentTheme = ref<ResolvedTheme>('light')

function syncTheme() {
  currentTheme.value = getResolvedTheme()
}

function handleToggle() {
  currentTheme.value = toggleTheme()
}

onMounted(() => {
  currentTheme.value = initializeTheme()
  window.addEventListener(THEME_CHANGE_EVENT, syncTheme)
})

onBeforeUnmount(() => window.removeEventListener(THEME_CHANGE_EVENT, syncTheme))
</script>

<template>
  <Button
    variant="outline"
    size="sm"
    :aria-label="currentTheme === 'dark' ? '切换为浅色主题' : '切换为深色主题'"
    @click="handleToggle"
  >
    <Sun v-if="currentTheme === 'dark'" :size="16" />
    <Moon v-else :size="16" />
  </Button>
</template>
