// docs/docs/views/00_微前端/00_micro-frontend/23.项目实战4：自定义封装micro-router路由适配/supply-chain/packages/ui-react/src/components/label.tsx
import * as LabelPrimitive from '@radix-ui/react-label'
import type { ComponentPropsWithoutRef } from 'react'

import { cn } from '../lib/utils'

export function Label({
  className,
  ...props
}: ComponentPropsWithoutRef<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root className={cn('text-sm font-medium leading-none', className)} {...props} />
  )
}

// docs/docs/views/00_微前端/00_micro-frontend/22.项目实战3：qiankun接入、登录与企业级认证架构/supply-chain/packages/ui-vue/src/components/Label.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'

import { cn } from '../lib/utils'

defineProps<{ for?: string; class?: HTMLAttributes['class'] }>()
</script>

<template>
  <label :for="$props.for" :class="cn('text-sm font-medium leading-none', $props.class)">
    <slot />
  </label>
</template>
